/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CardHistories: typeof import('./components/histories/components/CardHistories.vue')['default']
    CardImage: typeof import('./components/common/CardImage.vue')['default']
    CardSeries: typeof import('./components/series/components/CardSeries.vue')['default']
    Chip: typeof import('./components/common/Chip.vue')['default']
    Details: typeof import('./components/details/Details.vue')['default']
    DetailsPage: typeof import('./components/details/DetailsPage.vue')['default']
    Histories: typeof import('./components/histories/Histories.vue')['default']
    Loading: typeof import('./components/common/Loading.vue')['default']
    MarvelPage: typeof import('./components/common/MarvelPage.vue')['default']
    Observer: typeof import('./components/common/Observer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Series: typeof import('./components/series/Series.vue')['default']
  }
}
